# Методичка 3

##__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Решение:

а) Не удовлетворяет условиям $m\times{n}$<br>
б)$AB - 2\times{3}, BA$ нет<br>
в)$AB - 8\times{8}, BA - 3\times{3}$<br>
г)$AB, BA - 4\times4$<br>


##__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B = \begin{pmatrix}5 & -3 \\ 3 & 5 \end{pmatrix}$<br>
$A\times{B} = \begin{pmatrix}4 & -11 \\ 12 & -3 \end{pmatrix}$

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4,-1], [0,5]])

print(f'Сумма A и B:\n {A+B}')
print(f'Произведение A и B:\n {A.dot(B)}')

Сумма A и B:
 [[ 5 -3]
 [ 3  5]]
Произведение A и B:
 [[  4 -11]
 [ 12  -3]]


##__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A = \begin{pmatrix} 3 & 21 \\ 9 & -18 \end{pmatrix},$
$2B  = \begin{pmatrix} 0 & 10 \\ 4 & -2 \end{pmatrix},$
$4C  = \begin{pmatrix} 8 & -16 \\ 4 & 4 \end{pmatrix},$<br>
$3A - 2B + 4C = \begin{pmatrix} 11 & -5 \\ 9 & -12 \end{pmatrix}$

In [ ]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])

print(f'3A - 2B + 4C = \n{3*A-2*B+4*C}')

3A - 2B + 4C = 
[[ 11  -5]
 [  9 -12]]


#__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T} = \begin{pmatrix} 4 & 5 & 2 \\ 1 & -2 & 3\end{pmatrix}$<br>
$A\cdot A^{T} = \begin{pmatrix} 17 & 18 & 11 \\ 18 & 29 & 4 \\ 11 & 4 & 13\end{pmatrix}$<br>
$A^T\cdot A = \begin{pmatrix} 45 & 0 \\ 0 & 14\end{pmatrix}$

In [ ]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'A =\n {A}')
print(f'A.T=\n {A.T}')
print(f' A*A.T=\n {A @ A.T}')
print(f' A.T*A=\n {A.T @ A}')

A =
 [[ 4  1]
 [ 5 -2]
 [ 2  3]]
A.T=
 [[ 4  5  2]
 [ 1 -2  3]]
 A*A.T=
 [[17 18 11]
 [18 29  4]
 [11  4 13]]
 A.T*A=
 [[45  0]
 [ 0 14]]


##__5__*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy

In [ ]:
A = np.array([[4,1],[5,-2],[2,3]])
B = np.array([[3,5,-1],[-4,3,2]])
print(A)
print(B)
print(A @ B)

[[ 4  1]
 [ 5 -2]
 [ 2  3]]
[[ 3  5 -1]
 [-4  3  2]]
[[ 8 23 -2]
 [23 19 -9]
 [-6 19  4]]


In [ ]:
def matrix_cross(A, B):
  if len(A[0]) == len(B):    
    for i in range(len(A)):
      sum = 0      
      for j in range(len(B)):         
        sum += A[i][j]*B[j][i]
      print(sum)     
    return ''
  else:
    return 'Wrong dimensions!'

In [ ]:
matrix_cross(A,B)

8
19
4


''

# Методичка 4

##__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Решение:

а) $\sin{x}\cdot sin{x} - \cos{x}\cdot(-\cos{x}) = \sin^2{x} + \cos^2{x} = 1$<br>
б) Матрица треугольная $\Rightarrow 4\cdot5\cdot9=180$<br>
в) Для удобства вычислений берем последнюю строку: $7\cdot(12-15)-8\cdot(6-12)+9\cdot(5-8) = 0$

##__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

Решение:<br>
а) 16<br>
б) 4<br>
в) 32 (для матрицы 3*3)

##__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Решение:
Строки 1 и 2 линейно зависимы (2 строка получается домножением первой на -2) $\Rightarrow$ матрица вырожденная.

##__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Решение:<br>
а) 2<br>
б) 3